/**
 * CRM API
 * CRM API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Offer } from './offer';
import { ClientCommunicationReport } from './client-communication-report';


export interface Client { 
    id?: number;
    created?: string;
    changed?: string;
    name?: string | null;
    legalEntitiesNames?: string | null;
    domainNames?: string | null;
    contact?: string | null;
    diagnostics?: string | null;
    offers?: Array<Offer> | null;
    communicationReports?: Array<ClientCommunicationReport> | null;
}

