/**
 * CRM API
 * CRM API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommunicationReport } from './communication-report';
import { Offer } from './offer';


export interface Client { 
    id?: number;
    created?: string;
    changed?: string;
    name?: string | null;
    legalEntitiesNames?: string | null;
    domainNames?: string | null;
    contact?: string | null;
    diagnostics?: string | null;
    email?: string | null;
    offers?: Array<Offer> | null;
    commonCommunicationReports?: Array<CommunicationReport> | null;
    key?: string | null;
}

