/**
 * CRM API
 * CRM API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmailSettingsDto { 
    senderName?: string | null;
    senderEmail?: string | null;
    smtpHost?: string | null;
    port?: number;
    password?: string | null;
}

