/**
 * CRM API
 * CRM API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Offer } from './offer';
import { FileDatum } from './file-datum';
import { OfferFileType } from './offer-file-type';


export interface OfferFileDatum { 
    id?: number;
    created?: string;
    changed?: string;
    fileDatum?: FileDatum;
    fileDatumId?: number;
    offer?: Offer;
    offerId?: number;
    type?: OfferFileType;
}

