/**
 * CRM API
 * CRM API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OfferCheckStatus = 0 | 1 | 2;

export const OfferCheckStatus = {
    NUMBER_0: 0 as OfferCheckStatus,
    NUMBER_1: 1 as OfferCheckStatus,
    NUMBER_2: 2 as OfferCheckStatus
};

