/**
 * CRM API
 * CRM API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferPotential } from './offer-potential';


export interface OfferEditDto { 
    id?: number;
    productSystemType?: string | null;
    briefIndustryDescription?: string | null;
    offerCase?: string | null;
    description?: string | null;
    offerPoint?: string | null;
    recommendations?: string | null;
    otherDocumentation?: string | null;
    coveringLetter?: string | null;
    similarCases?: string | null;
    clientId?: number;
    newsLinks?: string | null;
    potential?: OfferPotential;
    stage?: string | null;
}

