/**
 * CRM API
 * CRM API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OfferPotential = 'Undefined' | 'NotSet' | 'Cold' | 'Warm' | 'Hot';

export const OfferPotential = {
    Undefined: 'Undefined' as OfferPotential,
    NotSet: 'NotSet' as OfferPotential,
    Cold: 'Cold' as OfferPotential,
    Warm: 'Warm' as OfferPotential,
    Hot: 'Hot' as OfferPotential
};

