/**
 * CRM API
 * CRM API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OfferCheckStatus = 'NotSet' | 'Approved' | 'Rejected';

export const OfferCheckStatus = {
    NotSet: 'NotSet' as OfferCheckStatus,
    Approved: 'Approved' as OfferCheckStatus,
    Rejected: 'Rejected' as OfferCheckStatus
};

