/**
 * CRM API
 * CRM API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OfferFileType = 'Undefined' | 'NotSet' | 'Photo' | 'Certificate' | 'TechPassport' | 'Card';

export const OfferFileType = {
    Undefined: 'Undefined' as OfferFileType,
    NotSet: 'NotSet' as OfferFileType,
    Photo: 'Photo' as OfferFileType,
    Certificate: 'Certificate' as OfferFileType,
    TechPassport: 'TechPassport' as OfferFileType,
    Card: 'Card' as OfferFileType
};

