/**
 * CRM API
 * CRM API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OfferPotential = 0 | 1 | 2 | 3 | 4;

export const OfferPotential = {
    NUMBER_0: 0 as OfferPotential,
    NUMBER_1: 1 as OfferPotential,
    NUMBER_2: 2 as OfferPotential,
    NUMBER_3: 3 as OfferPotential,
    NUMBER_4: 4 as OfferPotential
};

