/**
 * CRM API
 * CRM API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferCheckStatus } from './offer-check-status';


export interface OfferRuleDto { 
    id?: number;
    created?: string;
    changed?: string;
    offerId?: number;
    offerNumber?: number;
    clientName?: string | null;
    completed: boolean;
    task?: string | null;
    report?: string | null;
    deadline?: string;
    checkStatus?: OfferCheckStatus;
    checkRemark?: string | null;
}

