/**
 * CRM API
 * CRM API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferFileDatumDto } from './offer-file-datum-dto';
import { ClientDto } from './client-dto';
import { OfferRuleDto } from './offer-rule-dto';
import { OfferNewsbreakDto } from './offer-newsbreak-dto';
import { OfferFeedbackRequestDto } from './offer-feedback-request-dto';


export interface OfferDto { 
    id?: number;
    created?: string;
    changed?: string;
    number?: number;
    productSystemType?: string | null;
    briefIndustryDescription?: string | null;
    offerCase?: string | null;
    description?: string | null;
    offerPoint?: string | null;
    recommendations?: string | null;
    otherDocumentation?: string | null;
    coveringLetter?: string | null;
    similarCases?: string | null;
    newsLinks?: string | null;
    potential?: string | null;
    stage?: string | null;
    client?: ClientDto;
    clientId?: number;
    fileData?: Array<OfferFileDatumDto> | null;
    selectedSections: Array<string>;
    clientLink?: string;
    newsbreaks?: Array<OfferNewsbreakDto> | null;
    feedbackRequests?: Array<OfferFeedbackRequestDto> | null;
    rules: Array<OfferRuleDto>;
}

