/**
 * CRM API
 * CRM API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OfferFileType = 0 | 1 | 2 | 3 | 4 | 5;

export const OfferFileType = {
    NUMBER_0: 0 as OfferFileType,
    NUMBER_1: 1 as OfferFileType,
    NUMBER_2: 2 as OfferFileType,
    NUMBER_3: 3 as OfferFileType,
    NUMBER_4: 4 as OfferFileType,
    NUMBER_5: 5 as OfferFileType
};

