/**
 * CRM API
 * CRM API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Offer } from './offer';


export interface OfferVersion { 
    id?: number;
    created?: string;
    changed?: string;
    number?: number;
    data?: string | null;
    offer?: Offer;
    offerId?: number;
    author?: User;
    authorId?: number;
}

