/**
 * CRM API
 * CRM API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OfferSectionType = 'Undefined' | 'NotSet' | 'Description' | 'SystemType' | 'ShortDescription' | 'Case' | 'Recommendations' | 'SimilarCases' | 'RestDocuments' | 'CoveringLetter' | 'TechPassport' | 'Certificates' | 'BusinessCard';

export const OfferSectionType = {
    Undefined: 'Undefined' as OfferSectionType,
    NotSet: 'NotSet' as OfferSectionType,
    Description: 'Description' as OfferSectionType,
    SystemType: 'SystemType' as OfferSectionType,
    ShortDescription: 'ShortDescription' as OfferSectionType,
    Case: 'Case' as OfferSectionType,
    Recommendations: 'Recommendations' as OfferSectionType,
    SimilarCases: 'SimilarCases' as OfferSectionType,
    RestDocuments: 'RestDocuments' as OfferSectionType,
    CoveringLetter: 'CoveringLetter' as OfferSectionType,
    TechPassport: 'TechPassport' as OfferSectionType,
    Certificates: 'Certificates' as OfferSectionType,
    BusinessCard: 'BusinessCard' as OfferSectionType
};

