/**
 * CRM API
 * CRM API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferRule } from './offer-rule';
import { OfferFeedbackRequest } from './offer-feedback-request';
import { OfferFileDatum } from './offer-file-datum';
import { CommunicationReport } from './communication-report';
import { OfferNewsbreak } from './offer-newsbreak';
import { OfferVersion } from './offer-version';
import { Client } from './client';


export interface Offer { 
    id?: number;
    created?: string;
    changed?: string;
    number?: number;
    productSystemType?: string | null;
    briefIndustryDescription?: string | null;
    offerCase?: string | null;
    description?: string | null;
    offerPoint?: string | null;
    recommendations?: string | null;
    otherDocumentation?: string | null;
    coveringLetter?: string | null;
    similarCases?: string | null;
    newsLinks?: string | null;
    potential?: string | null;
    stage?: string | null;
    client?: Client;
    clientId?: number;
    fileData?: Array<OfferFileDatum> | null;
    selectedSections?: Array<string> | null;
    currentVersionNumber?: number;
    clientVersionNumber?: number;
    versions?: Array<OfferVersion> | null;
    clientLink?: string;
    newsbreaks?: Array<OfferNewsbreak> | null;
    feedbackRequests?: Array<OfferFeedbackRequest> | null;
    rules?: Array<OfferRule> | null;
    commonCommunicationReports?: Array<CommunicationReport> | null;
}

