/**
 * CRM API
 * CRM API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OfferRuleDto { 
    id?: number;
    created?: string;
    changed?: string;
    offerId?: number;
    completed: boolean;
    task?: string | null;
    deadline?: string;
}

