/**
 * CRM API
 * CRM API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Role = 0 | 1 | 2 | 3;

export const Role = {
    NUMBER_0: 0 as Role,
    NUMBER_1: 1 as Role,
    NUMBER_2: 2 as Role,
    NUMBER_3: 3 as Role
};

